name: Test, Build and Deploy Example to GitHub-Pages
on: [ push ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Setup stuff
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'yarn'
      - run: corepack enable

      # Check and build project
      - run: yarn install --immutable
      - run: yarn run check
      - run: yarn run build

      # Generate example
      - run: yarn workspace example generate:ci
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./example/out"
      - uses: actions/deploy-pages@v4

      # publish library
      - run: yarn run publish